site_name: Finance for Life
site_description: 'A practical introduction to all areas of finance for modern life'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/finance-for-life/'
repo_url: 'https://github.com/dmccreary/finance-for-life'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Course Description: course-description.md
  - Chapters:
    - Introduction: chapters/index.md
    - chapters/01-foundational-financial-concepts.md
    - chapters/smart-money-for-young-people.md
    - chapters/01-foundational-financial-concepts/index.md
    - chapters/02-banking-and-cash-management/index.md
    - chapters/03-budgeting-and-financial-planning/index.md
    - chapters/04-credit-and-debt-management/index.md
    - chapters/05-saving-and-investing/index.md
    - chapters/06-income-and-taxes/index.md
    - chapters/07-insurance-and-risk-management/index.md
    - chapters/08-major-purchases-and-loans/index.md
    - chapters/09-consumer-protection-and-financial-security/index.md
    - chapters/10-college-and-education-planning/index.md
    - chapters/11-career-planning-and-income/index.md
    - chapters/12-retirement-and-long-term-planning/index.md
    - chapters/mn-legislation.md
  - Prompts:
    - Introduction: prompts/index.md
    - Bloom Taxonomy: prompts/02-bloom-taxonomy.md
    - Concept Enumeration: prompts/04-concept-enumeration.md
    - Concept Dependency: prompts/06-concept-dependency.md
    - Concept Taxonomy: prompts/08-concept-taxonomy.md
    - Concept Classification: prompts/10-concept-classification.md
    - Glossary: prompts/12-glossary-prompt.md
    - List of MicroSims: prompts/14-list-of-microsims.md
    - US High School Topics: prompts/03-us-high-school-topics.md
  - MicroSims:
    - Introduction: sims/index.md
    - Learning Graph: sims/learning-graph/index.md
    - College Loan Payback: sims/college-loan-payback/index.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  # logo: img/logo.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX